/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

#include <Arduino.h>
#include <tcMenu.h>
#include "tcMenuAdaFruitGfx.h"
#include <graphics/MenuTouchScreenEncoder.h>
#include "tcMenuAdaTouchDriver.h"
#include <extras/DrawableTouchCalibrator.h>
#include <RuntimeMenuItem.h>
#include <IoAbstraction.h>
#include <EepromItemStorage.h>
#include <ArduinoEEPROMAbstraction.h>

// variables we declare that you may need to access
extern const PROGMEM ConnectorLocalInfo applicationInfo;
extern Adafruit_ST7789 gfx;
extern AdafruitDrawable gfxDrawable;
extern GraphicsDeviceRenderer renderer;
extern Adafruit_FT6206 touchDevice;
extern iotouch::AdaLibTouchInterrogator touchInterrogator;
extern MenuTouchScreenManager touchScreen;
extern tcextras::IoaTouchScreenCalibrator touchCalibrator;

// Any externals needed by IO expanders, EEPROMs etc


// Global Menu Item exports
extern AnalogMenuItem menuPort;
extern TextMenuItem menuPassword;
extern TextMenuItem menuAPName;
extern BackMenuItem menuBackNetworkSettings;
extern SubMenuItem menuNetworkSettings;
extern AnalogMenuItem menuRearRightTempIndex;
extern AnalogMenuItem menuRearLeftTempIndex;
extern AnalogMenuItem menuFrontRightTempIndex;
extern AnalogMenuItem menuFrontLeftTempIndex;
extern BackMenuItem menuBackTempSensorIndices;
extern SubMenuItem menuTempSensorIndices;
extern BackMenuItem menuBackHardwareSettings;
extern SubMenuItem menuHardwareSettings;
extern AnalogMenuItem menutrackMax;
extern AnalogMenuItem menutrackIdeal;
extern AnalogMenuItem menutrackMin;
extern BackMenuItem menuBackTrackSettings;
extern SubMenuItem menuTrackSettings;
extern AnalogMenuItem menustreetMax;
extern AnalogMenuItem menustreetIdeal;
extern AnalogMenuItem menustreetMin;
extern BackMenuItem menuBackStreetSettings;
extern SubMenuItem menuStreetSettings;
extern EnumMenuItem menuTemperatureScale;
extern EnumMenuItem menuCurrentMode;

// Provide a wrapper to get hold of the root menu item and export setupMenu
inline MenuItem& rootMenuItem() { return menuCurrentMode; }
void setupMenu();

// Callback functions must always include CALLBACK_FUNCTION after the return type
#define CALLBACK_FUNCTION


#endif // MENU_GENERATED_CODE_H
